<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>
<div class="row">

    <div class="page-header">
        <h1>Player list</h1>
    </div>

    <div class="btn-group" style="margin-bottom: 10px;">
        <a href="<?= $this->url('player/add'); ?>" class="btn btn-default">Add player</a>
    </div>

    <table class="table table-striped table-bordered">

        <thead>
            <tr>
                <th>Name</th>
                <th>Points</th>
                <th>Matches</th>
                <th></th>
            </tr>
        </thead>

        <tbody><?php foreach ($players as $player): ?>

            <tr>
                <td><a href="<?php echo $this->url('player/view', array('id' => $player->getId())); ?>"><?= $player->getName(); ?></a></td>
                <td class="right"><?= $player->getPoints(); ?></td>
                <td class="right"><?= $player->getMatchCount(); ?></td>
                <td><a href="<?php echo $this->url('player/edit', array('id' => $player->getId())); ?>">Edit</a></td>
            </tr>

        <?php endforeach; ?></tbody>

    </table>

</div>
