<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>
<h1>Player list</h1>

<div class="btn-group" style="margin-bottom: 10px;">
    <a href="<?= $this->url('player/add'); ?>" class="btn">Add player</a>
</div>

<table class="table table-striped">

    <tr>
        <th>Name</th>
    </tr>

    <?php foreach ($players as $player): ?>

    <tr>
        <td><a href="<?php echo $this->url('player/view', array('id' => $player->getId())); ?>"><?= $player->getName(); ?></a></td>
    </tr>

    <?php endforeach; ?>

</table>