<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>
<div class="row">

    <div class="span5">

        <h2>Recent Matches</h2>

        <table class="table table-striped">

        <?php foreach ($matches as $match): ?>
            <tr>
                <td><?php echo $match->getDate()->format("d.m. H:i"); ?></td>
                <td>

                    <?php if ($match instanceof \Application\Model\Entity\SingleMatch): ?>

                        <span class="<?php echo ($match->isTeamOneWinner() ? 'label label-success' : '') ?>">
                            <?php echo $match->getPlayer1()->getName(); ?>
                        </span>
                        <span class="muted">vs.</span>
                        <span class="<?php echo ($match->isTeamTwoWinner() ? 'label label-success' : '') ?>">
                            <?php echo $match->getPlayer2()->getName(); ?>
                        </span>

                    <?php elseif ($match instanceof \Application\Model\Entity\DoubleMatch): ?>

                        <span class="<?php echo ($match->isTeamOneWinner() ? 'label label-success' : '') ?>">
                            <?php echo $match->getTeamOne()->getName(); ?>
                        </span>
                        <span class="muted">vs.</span>
                        <span class="<?php echo ($match->isTeamTwoWinner() ? 'label label-success' : '') ?>">
                            <?php echo $match->getTeamTwo()->getName(); ?>
                        </span>

                    <?php endif; ?>

                    <br>

                    <small><span class="muted">Tournament:</span> <a href="<?php echo $this->url('tournament/show', array('id' => $match->getTournament()->getId())); ?>"><?php echo $match->getTournament()->getName(); ?></a></small>

                </td>
                <td>
                    <?php echo $this->matchResult($match); ?>
                </td>
            </tr>
        <?php endforeach; ?>

        </table>

    </div>

    <div class="span6 offset1">

        <h1>Tournaments</h1>

        <div class="row">

            <?php foreach ($tournaments as $tournament): ?>

                <div class="span3">
                    <h4><?php echo $tournament->getName(); ?></h4>

                    <?php if ($tournament instanceof \Application\Model\Entity\League): ?>

                        <?php echo $this->ranking($tournament, 999, new \Application\Model\LeaguePeriod($tournament->getStart(), date('Y'), date('m')), 3); ?>

                    <?php else: ?>

                        <p>The tournament is running</p>

                    <?php endif; ?>

                    <p>
                        <a href="<?php echo $this->url("tournament/show", array('id' => $tournament->getId())); ?>" class="btn btn-small">
                            Show
                        </a>
                    </p>
                </div>

            <?php endforeach; ?>

        </div>

    </div>

</div>