<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>
<div class="page-header">
    <h1>Add tournament</h1>
</div>

<?php echo $this->form()->openTag($form->setAttribute('class', 'form-horizontal')); ?>

<?php if ($form->hasValidated() && !$form->isValid()): ?>
<div class="alert alert-error">
    <strong>Validation problems:</strong> Please check your form input
</div>
<?php endif; ?>

<?php $messages = $form->get('name')->getMessages(); ?>
<div class="control-group<?php if (count($messages)): ?> error<?php endif; ?>">
    <?php $form->get('name')->setLabelAttributes(array('class' => 'control-label')); ?>
    <?php echo $this->formLabel($form->get('name')); ?>
    <div class="controls">
    <?php echo $this->formElement($form->get('name')); ?>
    <?php echo $this->formElementErrors()
            ->setMessageOpenFormat('<div class="help-inline">')
            ->setMessageSeparatorString('. ')
            ->setMessageCloseString('.</div>')
            ->render($form->get('name')); ?>
    </div>
</div>

<?php $messages = $form->get('games-per-match')->getMessages(); ?>
<div class="control-group<?php if (count($messages)): ?> error<?php endif; ?>">
    <?php $form->get('games-per-match')->setLabelAttributes(array('class' => 'control-label')); ?>
    <?php $form->get('games-per-match')->setAttributes(array('class' => 'input-mini')); ?>
    <?php echo $this->formLabel($form->get('games-per-match')); ?>
    <div class="controls">
    <?php echo $this->formElement($form->get('games-per-match')); ?>
    <?php echo $this->formElementErrors()
            ->setMessageOpenFormat('<div class="help-inline">')
            ->setMessageSeparatorString('. ')
            ->setMessageCloseString('.</div>')
            ->render($form->get('games-per-match')); ?>
    </div>
</div>

<?php $messages = $form->get('team-type')->getMessages(); ?>
<div class="control-group<?php if (count($messages)): ?> error<?php endif; ?>">
    <?php $form->get('team-type')->setLabelAttributes(array('class' => 'control-label')); ?>
    <?php echo $this->formLabel($form->get('team-type')); ?>
    <div class="controls">
    <?php $form->get('team-type')->setLabelAttributes(array('class' => 'radio')); ?>
    <?php echo $this->formElement($form->get('team-type')); ?>
    <?php echo $this->formElementErrors()
            ->setMessageOpenFormat('<div class="help-inline">')
            ->setMessageSeparatorString('. ')
            ->setMessageCloseString('.</div>')
            ->render($form->get('team-type')); ?>
    </div>
</div>

<?php $messages = $form->get('max-score')->getMessages(); ?>
<div class="control-group<?php if (count($messages)): ?> error<?php endif; ?>">
    <?php $form->get('max-score')->setLabelAttributes(array('class' => 'control-label')); ?>
    <?php $form->get('max-score')->setAttributes(array('class' => 'input-mini')); ?>
    <?php echo $this->formLabel($form->get('max-score')); ?>
    <div class="controls">
    <?php echo $this->formElement($form->get('max-score')); ?>
    <?php echo $this->formElementErrors()
            ->setMessageOpenFormat('<div class="help-inline">')
            ->setMessageSeparatorString('. ')
            ->setMessageCloseString('.</div>')
            ->render($form->get('max-score')); ?>
    </div>
</div>

<?php $messages = $form->get('start-date')->getMessages(); ?>
<div class="control-group<?php if (count($messages)): ?> error<?php endif; ?>">
    <?php $form->get('start-date')->setLabelAttributes(array('class' => 'control-label')); ?>
    <?php $form->get('start-date')->setAttributes(array('class' => 'input-small')); ?>
    <?php echo $this->formLabel($form->get('start-date')); ?>
    <div class="controls">
    <?php echo $this->formElement($form->get('start-date')); ?>
    <?php echo $this->formElementErrors()
            ->setMessageOpenFormat('<div class="help-inline">')
            ->setMessageSeparatorString('. ')
            ->setMessageCloseString('.</div>')
            ->render($form->get('start-date')); ?>
    </div>
</div>

<div class="form-actions">
    <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>