<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>
<div class="page-header">
    <h1>Add tournament</h1>
</div>

<?php echo $this->form()->openTag($form->setAttribute('class', 'form-horizontal')); ?>

<?php if ($form->hasValidated() && !$form->isValid()): ?>
<div class="alert alert-error">
    <strong>Validation problems:</strong> Please check your form input
</div>
<?php endif; ?>

<?php $messages = $form->get('name')->getMessages(); ?>
<div class="control-group<?php if (count($messages)): ?> error<?php endif; ?>">
    <?php $form->get('name')->setLabelAttributes(array('class' => 'control-label')); ?>
    <?php echo $this->formLabel($form->get('name')); ?>
    <div class="controls">
	<?php echo $this->formElement($form->get('name')); ?>
	<?php echo $this->formElementErrors()
			->setMessageOpenFormat('<div class="help-inline">')
			->setMessageSeparatorString('. ')
			->setMessageCloseString('.</div>')
			->render($form->get('name')); ?>
    </div>
</div>

<div class="form-actions">
    <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>