<h1>Playing in <?= $tournament->getName(); ?></h1>

<table class="table table-striped">

    <tr>
	<th>Name</th>
    </tr>

    <?php foreach ($tournament->getPlayers() as $player): ?>

    <tr>
	<td><?= $player->getName(); ?></td>
    </tr>

    <?php endforeach; ?>

</table>

<?php
echo $this->form()->openTag($addPlayerForm);
echo $this->formRow($addPlayerForm->get('player'));
echo $this->formSubmit($addPlayerForm->get('submit'));
echo $this->form()->closeTag();
?>
