<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>
<h1>Playing in <?= $tournament->getName(); ?></h1>

<table class="table table-striped">

    <tr>
	<th>Name</th>
    </tr>

    <?php foreach ($tournament->getPlayers() as $player): ?>

	<tr>
	    <td><?= $player->getName(); ?></td>
	</tr>

    <?php endforeach; ?>

</table>

<?php
echo $this->form()->openTag($addPlayerForm);
echo $this->formRow($addPlayerForm->get('player'));
echo $this->formSubmit($addPlayerForm->get('submit'));
echo $this->form()->closeTag();
?>