<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>
<div class="row">
    <div class="page-header">
        <h1><?php echo $tournament->getName(); ?> - Month <?php echo $period->getStart()->format('Y/m'); ?></h1>
    </div>
</div>

<div class="row">

    <div class="col-md-4">

        <h2>Ranking</h2>

        <?php echo $this->ranking($tournament, $period); ?>

    </div>

    <div class="col-md-8">

        <h2>Matches</h2>

        <?php if ($tournament->isSinglePlayer()): ?>


            <?php
                echo $this->partial(
                    'application/tournament/single-league-matches.phtml',
                    array(
                        'tournament'    => $tournament,
                        'players'       => $players,
                        'activePlayers' => $activePlayers,
                        'period'        => $period,
                        'matches'       => $matches
                    )
                );
            ?>

        <?php endif; ?>

        <?php if ($tournament->isTeams()): ?>

            <?php
                echo $this->partial(
                    'application/tournament/double-league-matches.phtml',
                    array(
                        'tournament'          => $tournament,
                        'players'             => $players,
                        'matches'             => $matches
                    )
                );
            ?>

            <a href="<?php echo $this->url('match/new', array('tid' => $tournament->getId())); ?>" class="btn btn-primary btn-large">Add match</a>

        <?php endif; ?>

    </div>

</div>

<?php echo $this->leaguePaginator($tournament, $period); ?>

<script>
    $(document).ready(function() {
        $('.match').click( function() {
            if( $('.popover').length > 0 ) {
                $('.popover').remove();
            }
            else {
                showResultPopover($(this));
                $('.popover').mouseleave( function() {
                    $(this).remove();
                });
            }
        });

        $('.match').hover(
            function() {
                var nextElClassName = $(this).next().attr('class');

                // only add element if not already added
                if( typeof  nextElClassName == 'undefined' || nextElClassName.indexOf('popover') < 0 ) {
                    showResultPopover($(this));
                }
            },
            function( event) {
                // just hide popover when mouse hits the underlaying td again
                if( event.relatedTarget.attributes[0].nodeValue != undefined &&
                    event.relatedTarget.attributes[0].nodeValue == 'matchscore' ) {
                    $('.popover').remove();
                }
            }
        );

    });
</script>
