<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>
<h1>List of tournaments</h1>

<div class="btn-group" style="margin-bottom: 10px;">
    <a href="<?= $this->url('tournament/add'); ?>" class="btn">Add tournament</a>
</div>

<table class="table table-striped table-hover">

    <tr>
        <th>Name</th>
    </tr>

    <?php foreach ($tournaments as $tournament): ?>

    <tr>
        <td>
            <?php echo $tournament->getId(); ?>
        </td>
    </tr>

    <?php endforeach; ?>

</table>