<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */

echo $this->doctype();

?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Fußi')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/components/bootstrap/dist/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/components/html5shiv/dist/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/components/bootstrap/dist/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/components/jquery/dist/jquery.min.js')
                                      ->prependFile($this->basePath() . '/js/main.js') ?>
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('dashboard') ?>">Fußi</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                    <li class=""><a href="<?php echo $this->url('dashboard') ?>">Home</a></li>
                    <li class="dropdown">
                        <a id="trnmnts" class="dropdown-toggle" data-toggle="dropdown" href="<?php echo $this->url('tournaments') ?>">Tournaments <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('tournaments') ?>" tabindex="-1" role="menuitem">Tournaments</a></li>
                            <li class="divider"></li>
                            <?php echo $this->tournamentList(); ?>
                        </ul>
                    </li>
                    <li class=""><a href="<?php echo $this->url('players') ?>">Players</a></li>
                </ul>
            </div>
        </nav>

        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p><small>
                    Fußi v. (development) -
                    Made with <span style="color: red;">♥</span> by <a href="https://github.com/feibeck/fussi/graphs/contributors">the Fussi team</a>
                    using
                        <a href="http://framework.zend.com">Zend Framework 2</a>,
                        <a href="http://doctrine-project.org">Doctrine</a>,
                        <a href="http://twitter.github.com/bootstrap/index.html">Twitter Bootstrap</a>.
                    Many thanks to
                        <a href="http://mayflower.de">Mayflower GmbH</a>
                    for sponsoring Mayday time!
                </small></p>
                <p>Feeds: <a href="/feed/recent-matches">Recent matches</a></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
