<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */

echo $this->doctype();

?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Fußi')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-assets/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/components/bootstrap-assets/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/components/html5shiv/dist/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/components/bootstrap-assets/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/components/jquery/jquery.min.js')
                                      ->prependFile($this->basePath() . '/js/main.js') ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('dashboard') ?>">Fußi</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class=""><a href="<?php echo $this->url('dashboard') ?>">Home</a></li>
                            <li class="dropdown">
                                <a id="trnmnts" class="dropdown-toggle" data-toggle="dropdown" role="button" href="<?php echo $this->url('tournaments') ?>">Tournaments
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="trnmnts" role="menu">
                                    <li role="presentation">
                                        <a href="<?php echo $this->url('tournaments') ?>" tabindex="-1" role="menuitem">Tournaments</a>
                                    </li>
                                    <li class="divider" role="presentation"></li>
                                    <?php echo $this->tournamentList(); ?>
                                </ul>
                            </li>
                            <li class=""><a href="<?php echo $this->url('players') ?>">Players</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p><small>
                    Fußi v. 0.2.0 -
                    Made with <span style="color: red;">♥</span> by
                        <a href="http://github.com/feibeck">feibeck</a>,
                        <a href="http://github.com/lorindol">lorindol</a>,
                        <a href="http://github.com/katrin-schneider">katrin-schneider</a>,
                        <a href="http://github.com/stevenklar">stevenklar</a>,
                        <a href="http://github.com/x3ro89">x3ro89</a> and
                        <a href="http://github.com/mkleinschnitz">mkleinschnitz</a> and
                        <a href="http://github.com/tsteur">tsteur</a>
                    using
                        <a href="http://framework.zend.com">Zend Framework 2</a>,
                        <a href="http://doctrine-project.org">Doctrine</a>,
                        <a href="http://twitter.github.com/bootstrap/index.html">Twitter Bootstrap</a>.
                    Many thanks to
                        <a href="http://mayflower.de">Mayflower GmbH</a>
                    for sponsoring Mayday time!
                </small></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
