<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>
<table class="table table-striped">
    <tr>
        <th></th>
        <th><small>Player</small></th>
        <th><small>Points</small></th>
        <th><small>Matches</small></th>
        <th><small>Goals</small></th>
    </tr>
    <?php /** @var \Application\Model\Ranking $ranking */ ?>
    <?php foreach ($ranking->getRanking($count) as $i => $rank): ?>
        <tr>
            <td><span class="badge badge-success"><?= $i + 1; ?></span></td>
            <td class="playerName"><a href="<?php echo $this->url('player/view', array('id' => $rank->getPlayer()->getId())); ?>"><?= $rank->getPlayer()->getName()?></a></td>
            <td><span class="badge badge-warning"><?= $rank->getScore(); ?></span></td>
            <td><span class="badge"><?= $rank->getMatchCount(); ?></span></td>
            <td><span><?= $rank->getGoals(); ?> : <?= $rank->getGoalsAgainst(); ?></span></td>
        </tr>
    <?php endforeach; ?>
</table>