<table class="table table-striped">
    <tr>
        <th></th>
        <th><small>Player</small></th>
        <th><small>Points</small></th>
        <th><small>Matches</small></th>
    </tr>
    <?php foreach ($ranking->getRanking($count) as $ranking): ?>
        <tr>
            <td><span class="badge badge-success"><?= ++$i; ?></span></td>
            <td class="playerName"><?= $ranking->getPlayer()->getName(); ?></td>
            <td><span class="badge badge-warning"><?= $ranking->getScore(); ?></span></td>
            <td><span class="badge"><?= $ranking->getMatchCount(); ?></span></td>
        </tr>
    <?php endforeach; ?>
</table>