<table class="table table-striped">
    <tr>
        <th></th>
        <th><small>Player</small></th>
        <th><small>Points</small></th>
        <th><small>Matches</small></th>
    </tr>
    <?php
    $i = 0;
    foreach ($ranking->getRanking($count) as $rank): ?>
        <tr>
            <td><span class="badge badge-success"><?= ++$i; ?></span></td>
            <td class="playerName <?php
                if ($rank->potential >= $tournamentPotential) {
                    echo "eligible";
                }?>"><?= $rank->getPlayer()->getName()?></td>
            <td><span class="badge badge-warning"><?= $rank->getScore(); ?></span></td>
            <td><span class="badge"><?= $rank->getMatchCount(); ?></span></td>
        </tr>
    <?php endforeach; ?>
</table>