<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>

<div class="row">

    <div class="page-header">
        <h1>Add tournament</h1>
    </div>

    <?php echo $this->form()->openTag($form->setAttribute('class', 'form-horizontal')); ?>

    <?php echo $this->tbsFormError($form); ?>

    <?php echo $this->tbsFormRow($form->get('name')); ?>

    <?php echo $this->tbsFormRow($form->get('match-mode')); ?>

    <?php $form->get('games-per-match')->setAttributes(array('class' => 'input-mini')); ?>
    <?php echo $this->tbsFormRow($form->get('games-per-match')); ?>

    <?php $form->get('max-score')->setAttributes(array('class' => 'input-mini')); ?>
    <?php echo $this->tbsFormRow($form->get('max-score')); ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary')); ?>
        </div>
    </div>

    <?php echo $this->form()->closeTag(); ?>

</div>