<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>
<h1>List of tournaments</h1>

<div class="btn-group" style="margin-bottom: 10px;">
    <a href="<?= $this->url('tournament/add-league'); ?>" class="btn">Add league</a>
    <a href="<?= $this->url('tournament/add-tournament'); ?>" class="btn">Add tournament</a>
</div>

<table class="table table-striped table-hover">

    <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Active</th>
        <th></th>
    </tr>

    <?php foreach ($tournaments as $tournament): ?>

    <tr>
        <td>
            <a href="<?= $this->url('tournament/show', array('id' => $tournament->getId())) ?>">
                <?php echo $tournament->getName(); ?>
            </a>
        </td>
        <td>
            <?php echo $tournament->getType(); ?>
        </td>
        <td>
            <?php echo ($tournament->isActive() ? 'yes' : 'no'); ?>
        </td>
        <td class="right">
            <a href="<?= $this->url('tournament/show', array('id' => $tournament->getId())) ?>" class="btn btn-mini">Show</a>
            <a href="<?= $this->url('tournament/players', array('id' => $tournament->getId())) ?>" class="btn btn-mini">Players</a>
        </td>
    </tr>

    <?php endforeach; ?>

</table>