<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>

<div class="row">

    <div class="page-header">
        <h1>Playing in <?= $tournament->getName(); ?></h1>
    </div>

    <table class="table table-striped table-bordered">

        <thead>
            <tr>
                <th>Name</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($tournament->getPlayers() as $player): ?>

            <tr>
                <td><?= $player->getName(); ?></td>
            </tr>

            <?php endforeach; ?>
        </tbody>

    </table>

    <h2>Add player to tournament</h2>

    <?php echo $this->form()->openTag($addPlayerForm->setAttribute('class', 'form-inline')); ?>
    <div class="form-group">
        <?php echo $this->formElement($addPlayerForm->get('player')->setAttribute('class', 'form-control')); ?>
    </div>

    <?php echo $this->formSubmit($addPlayerForm->get('submit')->setAttribute('class', 'btn btn-default')); ?>
    <?php echo $this->form()->closeTag(); ?>

</div>