<div class="row">

    <div class="page-header">
        <h1>Tournament setup: <?php echo $tournament->getName(); ?></h1>
    </div>

    <?php $ready = (count($tournament->getPlayers()) % 2 == 0 && count($tournament->getPlayers()) >= 4); ?>

    <?php if (!$ready): ?>
        <div class="alert alert-warning">
            <strong>Player count!</strong> You need an even number of players.
        </div>
    <?php endif; ?>

    <?php if ($tournament->isActive()): ?>
        <div class="alert alert-info">The tournament is currently running</div>
    <?php elseif ($tournament->isFinished()): ?>
        <div class="alert alert-info">The tournament is finished</div>
    <?php else: ?>
        <div class="btn-group" style="margin-bottom: 10px;">
            <?php $url = $this->url('tournament/start', array('id' => $tournament->getId())); ?>
            <a <?php if ($ready) echo 'href="' . $url . '"'; ?> class="btn btn-default<?php if (!$ready) echo ' disabled'; ?>">Start Tournament</a>
        </div>
    <?php endif; ?>

    <h2>Players</h2>

    <table class="table table-striped table-bordered">

        <thead>
            <tr>
                <th>Name</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($tournament->getPlayers() as $player): ?>

            <tr>
                <td><?= $player->getName(); ?></td>
            </tr>

            <?php endforeach; ?>
        </tbody>

    </table>

    <?php if (!$tournament->isActive() && !$tournament->isFinished()): ?>

        <?php echo $this->form()->openTag($addPlayerForm->setAttribute('class', 'form-inline')); ?>
        <div class="form-group">
            <?php echo $this->formElement($addPlayerForm->get('player')->setAttribute('class', 'form-control')); ?>
        </div>

        <?php echo $this->formSubmit($addPlayerForm->get('submit')->setAttribute('class', 'btn btn-default')); ?>
        <?php echo $this->form()->closeTag(); ?>

    <?php endif; ?>

</div>