<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>
<?php
    $form->prepare();
    echo $this->formElementErrors($form);
    echo $this->form()->openTag($form);
?>

<?php if ($form instanceof Application\Form\MatchFormDouble):?>

    <div class="row">

         <div class="col-md-5">
             <h2>Team 1</h2>

             <label>Attack</label> <?php echo $this->formElement($form->get('teamOneAttack')); ?>
             <label>Defence</label> <?php echo $this->formElement($form->get('teamOneDefence')); ?>
         </div>

         <div class="col-md-5">
             <h2>Team 2</h2>

             <label>Attack</label> <?php echo $this->formElement($form->get('teamTwoAttack')); ?>
             <label>Defence</label> <?php echo $this->formElement($form->get('teamTwoDefence')); ?>
         </div>

    </div>

<?php endif; ?>

<hr>

<?php
    echo $this->formGame($form->get('games'));
?>

<?php if ($tournament->isMatchModeBestOf()): ?>
    <p><a id="add_game_button" class="btn btn-default btn-xs" href="#">Add game</a></p>
<?php endif; ?>

<?php


    echo $this->formHidden($form->get('csrf'));
    echo $this->formElement($form->get('submit')->setAttribute("class", "btn btn-default"));

    echo $this->form()->closeTag();

?>
<?php echo $this->headScript()->prependFile($this->basePath() . '/js/fussiform.js'); ?>
<script type="text/javascript">

    var maxGameCount = <?php echo $tournament->getGamesPerMatch(); ?>;
   
    $(document).ready(function() {

        $("#add_game_button").click(add_game);
       
        var FuFo = new FussiForm();
        $('.game').each(function() {
            FuFo.connectFields($('.goals0',this),$('.goals1',this), <?php echo $tournament->getMaxScore(); ?>);
        })
    });

    function add_game() {
        var currentCount = $('#matchform tr.game').length;

        if (currentCount >= maxGameCount) {
            this.remove();
            return;
        }

        var template = $('.game-template').data('template');
        template = template.replace(/__index__/g, currentCount);
        template = template.replace(/Game&nbsp;0/g, "Game&nbsp;" + (currentCount + 1));

        var element = $(template).appendTo('#matchform');
        var FuFo = new FussiForm();

        FuFo.connectFields($('.goals0', element),$('.goals1', element), <?php echo $tournament->getMaxScore(); ?>);

        if (currentCount + 1 == maxGameCount) {
            this.remove();
        }

        return false;
    }

</script>