<?php
    /** @var $matches \Application\Entity\DoubleMatch[] */
?>
<table class="table">

    <tr>
        <th>Date</th>
        <th>Players</th>
        <th>Score</th>
        <th></th>
    </tr>

    <?php foreach ($matches as $match): ?>

        <tr>
            <td><?php echo $match->getDate()->format("d.m. H:i"); ?></td>
            <td>

                    <span class="<?php echo ($match->isTeamOneWinner() ? 'label label-success' : '') ?>">
                        <?php echo $match->getTeamOne()->getName(); ?>
                    </span>
                    <span class="muted">vs.</span>
                    <span class="<?php echo ($match->isTeamTwoWinner() ? 'label label-success' : '') ?>">
                        <?php echo $match->getTeamTwo()->getName(); ?>
                    </span>

            </td>
            <td>
                <?php echo implode(", ", $match->getGameResults()); ?>
            </td>
            <td>
                <a class="btn btn-mini" href="<?php echo $this->url('match/edit', array('mid' => $match->getId())); ?>">Edit</a>
            </td>
        </tr>

    <?php endforeach; ?>

</table>