<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */

/** @var $matches \Application\Entity\DoubleMatch[] */

?>
<table class="table">

    <tr>
        <th>Date</th>
        <th>Players</th>
        <th>Score</th>
        <th></th>
    </tr>

    <?php foreach ($matches as $match): ?>

        <tr>
            <td><?php echo $match->getDate()->format("d.m. H:i"); ?></td>
            <td>

                    <span class="<?php echo ($match->isTeamOneWinner() ? 'label label-success' : '') ?>">
                        <?php echo $match->getTeamOne()->getName(); ?>
                    </span>
                    <span class="muted">vs.</span>
                    <span class="<?php echo ($match->isTeamTwoWinner() ? 'label label-success' : '') ?>">
                        <?php echo $match->getTeamTwo()->getName(); ?>
                    </span>

            </td>
            <td>
                <?php echo $this->matchResult($match); ?>
            </td>
            <td>
                <a class="btn btn-mini" href="<?php echo $this->url('match/edit', array('mid' => $match->getId())); ?>">Edit</a>
            </td>
        </tr>

    <?php endforeach; ?>

</table>