<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>
<div class="row">
    <div class="span12">
        <h1><?php echo $tournament->getName(); ?> - Month <?php echo $date->format('Y/m'); ?></h1>
    </div>
</div>

<hr>

<div class="row">

    <div class="span4">

        <h2>Ranking <span class="icon-info-sign" id="toggleInfo"></span></h2>

        <table id="infoBox">
            <tr>
                <th>
                    Maximum Points
                </th>
                <td>
                    <?php echo (count($players) - 1) * 2; ?>
                </td>
            </tr>
            <tr>
                <th>
                    Maximum Matches
                </th>
                <td>
                    <?php echo (count($players) - 1); ?>
                </td>
            </tr>
            <tr>
                <th>
                    Current Potential
                </th>
                <td>
                   <?php $tournamentPotential =  $ranking->getPotential(count($players)-1);
                         echo $tournamentPotential; ?>
                </td>
            </tr>

        </table>

        <?php echo $this->ranking($tournament, $tournamentPotential, $date->format("Y"), $date->format("m")); ?>

    </div>

    <div class="span8">

        <h2>Matches</h2>

        <?php if ($tournament->isSinglePlayer()): ?>


            <?php
                echo $this->partial(
                    'application/index/single-league-matches.phtml',
                    array(
                        'tournament'    => $tournament,
                        'players'       => $players,
                        'activePlayers' => $activePlayers,
                        'date'          => $date,
                        'matches'       => $matches
                    )
                );
            ?>

        <?php endif; ?>

        <?php if ($tournament->isTeams()): ?>

            <?php
                echo $this->partial(
                    'application/index/double-league-matches.phtml',
                    array(
                        'tournament'          => $tournament,
                        'players'             => $players,
                        'date'                => $date,
                        'matches'             => $matches
                    )
                );
            ?>

            <a href="<?php echo $this->url('match/new', array('tid' => $tournament->getId())); ?>" class="btn btn-primary btn-large">Add match</a>

        <?php endif; ?>

    </div>

</div>

<?php
    $prev = clone($date);
    $prev->modify("-1 month");

    $disablePrev = $prev < $startDate;

    $prev = $this->url('tournament/show', array('id' => $tournament->getId(), 'year' => $prev->format('Y'), 'month' => $prev->format('m')));

    $next = clone($date);
    $next->modify("+1 month");
    $next = $this->url('tournament/show', array('id' => $tournament->getId(), 'year' => $next->format('Y'), 'month' => $next->format('m')));

    $now = new \DateTime();
    $disableNext = $now->format('Ym') == $date->format('Ym');
?>

<ul class="pager">
    <li class="previous <?php echo $disablePrev ? 'disabled' : ''; ?>">
        <a href="<?php echo $disablePrev ? '#' : $prev; ?>">&larr; Older</a>
    </li>
    <li class="next <?php echo $disableNext ? 'disabled' : ''; ?>">
        <a href="<?php echo $disableNext ? '#' : $next; ?>">Newer &rarr;</a>
    </li>
</ul>

<script>
    $(document).ready(function() {
        //$('.match').popover({html: true});

        $('.match').click( function() {
            if( $('.popover').length > 0 ) {
                $('.popover').remove();
            }
            else {
                showResultPopover($(this));
                $('.popover').mouseleave( function() {
                    $(this).remove();
                });
            }
        });

        $('.match').hover(
            function() {
                var nextElClassName = $(this).next().attr('class');

                // only add element if not already added
                if( typeof  nextElClassName == 'undefined' || nextElClassName.indexOf('popover') < 0 ) {
                    showResultPopover($(this));
                }
            },
            function( event) {
                // just hide popover when mouse hits the underlaying td again
                if( event.relatedTarget.attributes[0].nodeValue != undefined &&
                    event.relatedTarget.attributes[0].nodeValue == 'matchscore' ) {
                    $('.popover').remove();
                }
            }
        );

        $('#toggleInfo').click(function(){
            $('#infoBox').toggle();
            $('td.playerName.eligible').toggleClass('bold');
        })
        $('#infoBox').hide();
    });
</script>
