<div class="row">
    <div class="span12">
        <h1><?php echo $tournament->getName(); ?> - Month <?php echo $date->format('Y/m'); ?></h1>
    </div>
</div>

<hr>

<div class="row">

    <div class="span4">

        <h2>Ranking <span class="icon-info-sign" id="toggleInfo"></span></h2>

        <table id="infoBox">
            <tr>
                <th>
                    Maximum Points
                </th>
                <td>
                    <?php echo (count($players) - 1) * 2; ?>
                </td>
            </tr>
            <tr>
                <th>
                    Maximum Matches
                </th>
                <td>
                    <?php echo (count($players) - 1); ?>
                </td>
            </tr>
            <tr>
                <th>
                    Current Potential
                </th>
                <td>
                   <?php echo $ranking->getPotential(); ?>
                </td>
            </tr>

        </table>
        <table class="table">
            <tr>
                <th></th>
                <th>Player</th>
                <th>Points</th>
                <th>Matches</th>
            </tr>
            <?php foreach ($ranking->getRanking() as $ranking): ?>
                <tr>
                    <td><span class="badge badge-success"><?= ++$i; ?></span></td>
                    <td class="playerName"><?= $ranking->getPlayer()->getName(); ?></td>
                    <td><span class="badge badge-warning"><?= $ranking->getScore(); ?></span></td>
                    <td><span class="badge"><?= $ranking->getMatchCount(); ?></span></td>
                </tr>
            <?php endforeach; ?>
        </table>

    </div>

    <div class="span8">

        <?php if ($tournament->isSinglePlayer()): ?>

        <h2>Matches</h2>

        <table class="table matches">

            <tr>

                 <td></td>

            <?php for ($i = 0; $i < count($players) - 1; $i++): $player1 = $players[$i]; ?>

                 <th class="matchscore"><?php echo $player1->getName(); ?></th>

            <?php endfor; ?>

            </tr>

            <?php for ($row = count($players) -1; $row > 0; $row--): $player1 = $players[$row]; ?>

                <tr>
                    <th><?php echo $player1->getName(); ?></th>

                    <?php for ($column = 0; $column < count($players) - 1; $column++): $player2 = $players[$column]; ?>


                        <?php if ($column > $row - 1): ?>
                            <td></td>
                        <?php else: ?>
                            <td class="matchscore"><?php echo $this->match($date, $tournament, $matches, $player1, $player2); ?></td>
                        <?php endif; ?>

                    <?php endfor; ?>

                </tr>

            <?php endfor; ?>

        </table>

        <?php endif; ?>

        <?php if ($tournament->isTeams()): ?>

            <a href="<?php echo $this->url('match/add', array('tid' => $tournament->getId())); ?>" class="btn btn-primary btn-large">Add match</a>

        <?php endif; ?>

    </div>

</div>

<?php
    $prev = clone($date);
    $prev->modify("-1 month");

    $disablePrev = $prev < $startDate;

    $prev = $this->url('tournament/show', array('id' => $tournament->getId(), 'year' => $prev->format('Y'), 'month' => $prev->format('m')));

    $next = clone($date);
    $next->modify("+1 month");
    $next = $this->url('tournament/show', array('id' => $tournament->getId(), 'year' => $next->format('Y'), 'month' => $next->format('m')));

    $now = new \DateTime();
    $disableNext = $now->format('Ym') == $date->format('Ym');
?>

<ul class="pager">
    <li class="previous <?php echo $disablePrev ? 'disabled' : ''; ?>">
        <a href="<?php echo $disablePrev ? '#' : $prev; ?>">&larr; Older</a>
    </li>
    <li class="next <?php echo $disableNext ? 'disabled' : ''; ?>">
        <a href="<?php echo $disableNext ? '#' : $next; ?>">Newer &rarr;</a>
    </li>
</ul>

<script>
    $(document).ready(function() {
        //$('.match').popover({html: true});

        $('.match').click( function() {
            if( $('.popover').length > 0 ) {
                $('.popover').remove();
            }
            else {
                showResultPopover($(this));
                $('.popover').mouseleave( function() {
                    $(this).remove();
                });
            }
        });

        $('.match').hover(
            function() {
                var nextElClassName = $(this).next().attr('class');

                // only add element if not already added
                if( typeof  nextElClassName == 'undefined' || nextElClassName.indexOf('popover') < 0 ) {
                    showResultPopover($(this));
                }
            },
            function( event) {
                // just hide popover when mouse hits the underlaying td again
                if( event.relatedTarget.attributes[0].nodeValue != undefined &&
                    event.relatedTarget.attributes[0].nodeValue == 'matchscore' ) {
                    $('.popover').remove();
                }
            }
        );

        $('#toggleInfo').click(function(){
            $('#infoBox').toggle();
            $('td.playerName.eligible').toggleClass('bold');
        })
        $('#infoBox').hide();
    });
</script>
