<h1>Enter Matchresult</h1>
<?php echo $this->headScript()->prependFile($this->basePath() . '/js/fussiform.js'); ?>
<script type="text/javascript">
    $(document).ready(function() {
        var FuFo = new FussiForm();
        FuFo.connectFields(
            '<?php echo $form->get('goalsGame1Player1')->getAttribute('id'); ?>',
            '<?php echo $form->get('goalsGame1Player2')->getAttribute('id'); ?>'
        );
        FuFo.connectFields(
            '<?php echo $form->get('goalsGame2Player1')->getAttribute('id'); ?>',
            '<?php echo $form->get('goalsGame2Player2')->getAttribute('id'); ?>'
        );
    });
</script>

<div class="row">
    <div class="span5">

        <?php echo $this->form()->openTag($form); ?>

        <table class="table" id="matchform">
            <tr>
                <th></th>
                <th><?php echo $player1->getName(); ?></th>
                <th>vs.</th>
                <th><?php echo $player2->getName(); ?></th>
            </tr>
            <tr>
                <th>Game 1</th>
                <td><?php echo $this->formElement($form->get('goalsGame1Player1')); ?></td>
                <td>:</td>
                <td><?php echo $this->formElement($form->get('goalsGame1Player2')); ?></td>
            </tr>
            <tr>
                <th>Game 2</th>
                <td><?php echo $this->formElement($form->get('goalsGame2Player1')); ?></td>
                <td>:</td>
                <td><?php echo $this->formElement($form->get('goalsGame2Player2')); ?></td>
            </tr>
        </table>

        <input type="submit" class="btn btn-big btn-primary" value="Speichern" />
        <input type="reset" id="cancelEditMatchResult" class="btn btn-big" value="Abbrechen" />

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
