<?php
/**
 * View script
 *
 * @copyright Copyright (c) 2013 The Fußi-Team
 * @license   THE BEER-WARE LICENSE (Revision 42)
 *
 * "THE BEER-WARE LICENSE" (Revision 42):
 * The Fußi-Team wrote this software. As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy us a beer in return.
 */
?>
<table class="table matches">

    <tr>

         <td></td>

    <?php for ($i = 0; $i < count($players) - 1; $i++): $player1 = $players[$i]; ?>
        <?php
            $active = $activePlayers->contains($player1);
            if (!$active) {
                $inactiveColumns[$i] = true;
            }
        ?>
        <th class="matchscore<?php if(!$active) echo ' inactive'; ?>"><?php echo $player1->getName(); ?></th>

    <?php endfor; ?>

    </tr>

    <?php for ($row = count($players) -1; $row > 0; $row--): $player1 = $players[$row];  ?>
    <?php $active = $activePlayers->contains($player1); ?>

        <tr>
            <th <?php if(!$active) echo "class='inactive'" ?>><?php echo $player1->getName(); ?></th>

            <?php for ($column = 0; $column < count($players) - 1; $column++): $player2 = $players[$column]; ?>


                <?php if ($column > $row - 1): ?>
                    <td></td>
                <?php else: ?>
                    <td class="matchscore<?php if(!$active || isset($inactiveColumns[$column]) && $inactiveColumns[$column]) echo ' inactive';?>">
                        <?php echo $this->match($period, $tournament, $matches, $player1, $player2); ?>
                    </td>
                <?php endif; ?>

            <?php endfor; ?>

        </tr>

    <?php endfor; ?>

</table>