<table class="table matches">

    <tr>

         <td></td>

    <?php for ($i = 0; $i < count($players) - 1; $i++): $player1 = $players[$i]; ?>
        <?php
            $active = $activePlayers->contains($player1);
            if (!$active) {
                $inactiveColumns[$i] = true;
            }
        ?>
        <th class="matchscore<?php if(!$active) echo ' inactive'; ?>"><?php echo $player1->getName(); ?></th>

    <?php endfor; ?>

    </tr>

    <?php for ($row = count($players) -1; $row > 0; $row--): $player1 = $players[$row];  ?>
    <?php $active = $activePlayers->contains($player1); ?>

        <tr>
            <th <?php if(!$active) echo "class='inactive'" ?>><?php echo $player1->getName(); ?></th>

            <?php for ($column = 0; $column < count($players) - 1; $column++): $player2 = $players[$column]; ?>


                <?php if ($column > $row - 1): ?>
                    <td></td>
                <?php else: ?>
                    <td class="matchscore<?php if(!$active || $inactiveColumns[$column]) echo ' inactive';?>">
                        <?php echo $this->match($date, $tournament, $matches, $player1, $player2); ?>
                    </td>
                <?php endif; ?>

            <?php endfor; ?>

        </tr>

    <?php endfor; ?>

</table>